server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://106.12.31.210:3306/exam?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: Wu1994821!
#     url: jdbc:mysql://180.76.247.165:3306/exam?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
#     username: root
#     password: Sxnsyh!mysql

mybatis:
  mapper-locations: classpath:mapper/*.xml

  # pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql